---
- name: Copy helm binary from download dir
  synchronize:
    src: "{{ local_release_dir }}/linux-{{ image_arch }}/helm"
    dest: "{{ bin_dir }}/helm"
    compress: no
    perms: yes
    owner: no
    group: no
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  when:
    - inventory_hostname == groups['kube-master'][0]
  tags:
    - helm
    - upgrade

- name: Set helm binary permissions
  file:
    path: "{{ bin_dir }}/helm"
    mode: "0755"
    state: file
  when:
    - inventory_hostname == groups['kube-master'][0]
  tags:
    - helm
    - upgrade

- name: Install helm bash completion
  shell: "{{ bin_dir }}/helm completion bash >/etc/bash_completion.d/helm.sh"
  ignore_errors: True
  when:
    - ansible_os_family in ["Debian","RedHat"]
    - inventory_hostname == groups['kube-master'][0]
  tags:
    - helm

- name: Set helm bash completion file permissions
  file:
    path: /etc/bash_completion.d/helm.sh
    owner: root
    group: root
    mode: 0755
  ignore_errors: True
  when:
    - ansible_os_family in ["Debian","RedHat"]
    - inventory_hostname == groups['kube-master'][0]
  tags:
    - helm
    - upgrade

- name: Add helm stable repo
  command: "{{ bin_dir }}/helm repo add stable {{ helm_stable_repo_url }}"
  when:
    - helm_stable_repo_url is defined
    - inventory_hostname == groups['kube-master'][0]
  tags:
    - helm
    - upgrade
